modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="mistexturas"
version="1.0.0"
displayName="Mis Texturas"
description='''
Texturas adicionales para el modpack.
'''

[[dependencies.mistexturas]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.mistexturas]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
